{% set name = "taipy-config" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/taipy-config-{{ version }}.tar.gz
  sha256: 2f01184c73b38413e7fc822cbc5803ca23313d0908775aee59794f709c3f4d92

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - toml >=0.10,<0.11
    - deepdiff >=6.2,<6.3

test:
  imports:
    - taipy

about:
  home: https://github.com/avaiga/taipy-config
  summary: A Taipy package dedicated to easily configure a Taipy application.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
